"""added usdc logging in order

Revision ID: 276e4310231c
Revises: 0592f5d92ca8
Create Date: 2025-07-26 06:07:49.261378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '276e4310231c'
down_revision: Union[str, Sequence[str], None] = '0592f5d92ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_usdc', sa.Numeric(precision=14, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('amount_usdc')

    # ### end Alembic commands ###
