"""added is_winner in payout table

Revision ID: 3439e63c9c22
Revises: f72e1c25a28c
Create Date: 2025-07-29 05:19:10.598995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3439e63c9c22'
down_revision: Union[str, Sequence[str], None] = 'f72e1c25a28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_winner', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout_logs', schema=None) as batch_op:
        batch_op.drop_column('is_winner')

    # ### end Alembic commands ###
