"""added relationship between market and market outcome proper v2

Revision ID: 8eedb78d4b53
Revises: c1cf953be3fa
Create Date: 2025-07-26 05:24:27.922225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8eedb78d4b53'
down_revision: Union[str, Sequence[str], None] = 'c1cf953be3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
