"""added relationship between market and market outcome proper v3

Revision ID: 0592f5d92ca8
Revises: 8eedb78d4b53
Create Date: 2025-07-26 05:28:34.936867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0592f5d92ca8'
down_revision: Union[str, Sequence[str], None] = '8eedb78d4b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
