"""renamed slug to market slug

Revision ID: 30691f4bc299
Revises: 80dfabc926ca
Create Date: 2025-07-19 02:01:26.170822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30691f4bc299'
down_revision: Union[str, Sequence[str], None] = '80dfabc926ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('market_slug')

    # ### end Alembic commands ###
