"""in markel_change_log made change_type a Enum

Revision ID: 5a1981257653
Revises: 2836dd27d986
Create Date: 2025-07-18 03:37:40.054585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a1981257653'
down_revision: Union[str, Sequence[str], None] = '2836dd27d986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_change_logs', schema=None) as batch_op:
        batch_op.alter_column('change_type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('ADDED', 'DELETED', name='marketchangetype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_change_logs', schema=None) as batch_op:
        batch_op.alter_column('change_type',
               existing_type=sa.Enum('ADDED', 'DELETED', name='marketchangetype'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
