"""initial

Revision ID: 66a750ebd885
Revises: 
Create Date: 2025-07-26 03:20:27.390647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66a750ebd885'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change_type', sa.Enum('ADDED', 'DELETED', name='marketchangetype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets',
    sa.Column('condition_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_tradable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_table('tracked_markets',
    sa.Column('condition_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enable_order_book', sa.Boolean(), nullable=False),
    sa.Column('accepting_orders', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('market_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('market_outcomes',
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outcome_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['market'], ['markets.condition_id'], ),
    sa.PrimaryKeyConstraint('market', 'token')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('balance >= 0', name='balance_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', name='ordertype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIAL', 'FILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('shares', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price >= 0', name='_order_price_non_negative'),
    sa.CheckConstraint('shares >= 0', name='_order_shares_non_negative'),
    sa.ForeignKeyConstraint(['market', 'token'], ['market_outcomes.market', 'market_outcomes.token'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('user_positions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('shares >= 0', name='_user_shares_non_negative'),
    sa.ForeignKeyConstraint(['market', 'token'], ['market_outcomes.market', 'market_outcomes.token'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'market', 'token')
    )
    op.create_table('order_fills',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fill_shares', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('fill_price >= 0', name='_fill_price_non_negative'),
    sa.CheckConstraint('fill_shares >= 0', name='_fill_shares_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('fill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_fills')
    op.drop_table('user_positions')
    op.drop_table('orders')
    op.drop_table('user_profiles')
    op.drop_table('market_outcomes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tracked_markets')
    op.drop_table('markets')
    op.drop_table('market_change_logs')
    # ### end Alembic commands ###
