"""added slug to market tracker models

Revision ID: 80dfabc926ca
Revises: 5a1981257653
Create Date: 2025-07-19 01:32:02.457736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80dfabc926ca'
down_revision: Union[str, Sequence[str], None] = '5a1981257653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_markets', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
