"""added is_winner to market_outcome

Revision ID: f48154b3bedf
Revises: 8591b890abba
Create Date: 2025-07-28 21:33:00.920715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f48154b3bedf'
down_revision: Union[str, Sequence[str], None] = '8591b890abba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_outcomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_winner', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_outcomes', schema=None) as batch_op:
        batch_op.drop_column('is_winner')

    # ### end Alembic commands ###
